import { createSlice } from '@reduxjs/toolkit';

const initialState = {
    isAuthenticated: false,
    user: null,
    loginError: null,
};

export const authSlice = createSlice({
    name: 'auth',
    initialState,
    reducers: {
        login: (state, action) => {
            state.isAuthenticated = true;
            state.user = action.payload;
            state.loginError = null;
            console.log("User:", state.user, "isAuthenticated:", state.isAuthenticated)
        },
        logout: (state) => {
            state.isAuthenticated = false;
            state.user = null;
        },
        loginFailure: (state, action) => {
            state.isAuthenticated = false;
            state.loginError = action.payload;
        },
        // Add a register action if needed
        // register: (state, action) => {
        //   // Update state with registration details
        // },
    },
});

// Action creators generated by createSlice
export const { login, logout, loginFailure } = authSlice.actions;

export default authSlice.reducer;